sick_scan2: # configuration for sick_scan2_tim_240: For compatibility with ros versions previous to foxy, node and parameter name changed to sick_scan2 for all supported scanner. The type of scanner is configured by scanner_name only.
  ros__parameters:
    hostname : "20.50.0.5"
    frame_id : "hokuyo_link"
    scanner_name : "sick_tim_240"
    port : 2111
    min_ang : -2.094395102 #in lidar cordinate frame  see ../doc/3d_coordinate_system_comp.png
    max_ang : +2.094395102 #in lidar cordinate frame  see ../doc/3d_coordinate_system_comp.png
